version: '3.7'
services:
  control:
    volumes:
      - ${GOPATH}/bin:/gobin # Mounts $GOPATH/bin on host to /gobin for easy access to binaries.
  jaeger:
    networks:
      - jepsen
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    hostname: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
